config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get 'homes/about' => 'homes#about', as: 'about'

  resources :post_images, only: [:index, :show, :create, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :post_image
end

app/models/post_image.rb
class PostImage < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :shop_name, presence: true
  validates :image, presence: true

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/default-image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :following, class_name: "User"
  belongs_to :follower, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :post_images, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id
  has_many :followings, through: :active_relationships, source: :follower
  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
  has_many :followers, through: :passive_relationships, source: :following
  has_one_attached :profile_image

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/default-image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  def followed_by?(user)
    passive_relationships.find_by(following_id: user.id).present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    post_images_path
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    post_image = PostImage.find(params[:post_image_id])
    favorite = current_user.favorites.new(post_image_id: post_image.id)
    favorite.save
    redirect_to request.referer
  end

  def destroy
    post_image = PostImage.find(params[:post_image_id])
    favorite = current_user.favorites.find_by(post_image_id: post_image.id)
    favorite.destroy
    redirect_to request.referer
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController

  def create
    post_image = PostImage.find(params[:post_image_id])
    comment = current_user.post_comments.new(post_comment_params)
    comment.post_image_id = post_image.id
    comment.save
    redirect_to request.referer
  end

  def destroy
    PostComment.find(params[:id]).destroy
    redirect_to request.referer
  end

  private

  def post_comment_params
    params.require(:post_comment).permit(:comment)
  end
end

app/controllers/post_images_controller.rb
class PostImagesController < ApplicationController
  def index
    @post_images = PostImage.all
    @post_image = PostImage.new
  end

  def show
    @post_image = PostImage.find(params[:id])
    @post_comment = PostComment.new
  end

  def create
    @post_image = PostImage.new(post_image_params)
    @post_image.user_id = current_user.id
    if @post_image.save
      redirect_to request.referer
    else
      @post_images = PostImage.all
      render :index
    end
  end

  def edit
  end

  def destroy
    @post_image = PostImage.find(params[:id])
    @post_image.destroy
    redirect_to post_images_path
  end

  private

  def post_image_params
    params.require(:post_image).permit(:shop_name, :image, :caption)
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    follow = current_user.active_relationships.build(follower_id: params[:user_id])
    follow.save
    redirect_to request.referer
  end

  def destroy
    follow = current_user.active_relationships.find_by(follower_id: params[:user_id])
    follow.destroy
    redirect_to request.referer
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @post_images = @user.post_images
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path
  end

  def follows
    user = User.find(params[:id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:id])
    @users = user.followers
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/_btn.html.erb
<% if post_image.favorited_by?(current_user) %>
  <p>
    <%= link_to post_image_favorites_path(post_image), method: :delete do %>
      ♥<%= post_image.favorites.count %>
    <% end %>
  </p>
<% else %>
  <p>
    <%= link_to post_image_favorites_path(post_image), method: :post do %>
      ♡<%= post_image.favorites.count %>
    <% end %>
  </p>
<% end %>

app/views/homes/about.html.erb
<h2>About</h2>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class='mx-auto col-11 col-sm-10 col-lg-8 col-xl-6'>
      <h1>meshiterro</h1>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to 'Log in', new_user_session_path, class:"btn btn-info btn-sm btn-block mb-3 sign_in" %>
        </div>
        <div class="row">
          <%= link_to 'Sign up', new_user_registration_path, class:"btn btn-success btn-sm mb-3 btn-block sign_up" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="bg-dark text-white pt-5 pd-4">
  <div class='container mt-5'>
  	<div class='row'>
    	<div class='mx-auto'>
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="shadow-sm">
  <nav class="navbar navbar-expand-lg navbar-light">
    <div class="container">
      <a class="navbar-brand p-3" href="/"><span>Meshiterro</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to '投稿一覧', post_images_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to 'ユーザー一覧', users_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to 'マイページ', user_path(current_user.id), class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'nav-link text-dark' %>
            </li>

          <% else %>
            <li class="nav-item">
              <%= link_to "新規登録", new_user_registration_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to "ログイン", new_user_session_path, class: 'nav-link text-dark' %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Meshiterro2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <%= render 'layouts/header' %>
    <main>
      <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/post_comments/_count.html.erb
<p>コメント件数: <%= post_image.post_comments.count %></p>

app/views/post_comments/_form.html.erb
<%= form_with model: [post_image, post_comment] do |f| %>
  <%= f.text_area :comment, row: '5', placeholder: "コメント" %>
  <%= f.submit "送信" %>
<% end %>

app/views/post_comments/_index.html.erb
<% post_image.post_comments.each do |post_comment| %>
  <p><%= image_tag post_comment.user.get_profile_image(100, 100) %></p>
  <%= post_comment.user.name %>
  <%= post_comment.created_at.strftime('%Y/%m/%d') %><%= post_comment.comment %>
  <% if post_comment.user == current_user %>
    <%= link_to "削除", post_image_post_comment_path(post_comment.post_image, post_comment), method: :delete %>
  <% end %>
<% end %>

app/views/post_images/_form.html.erb
<h3>投稿</h3>
<% if post_image.errors.any? %>
  <%= post_image.errors.count %>件のエラーが発生しました
  <ul>
    <% post_image.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: post_image, local: true do |f| %>
  <div>
    <%= f.label :image %>
    <%= f.file_field :image, accept: "image/*" %>
  </div>
  <div>
    <%= f.label :shop_name %>
    <%= f.text_field :shop_name %>
  </div>
  <div>
    <%= f.label :caption %>
    <%= f.text_area :caption %>
  </div>
  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/post_images/_index.html.erb
<div class="card-list-container py-5">
  <% post_images.each do |post_image| %>
    <div class="card w-100 mx-auto mt-4 shadow-lg">
      <%= link_to(post_image_path(post_image.id)) do %>
        <%= image_tag post_image.get_image, class:"card-img-top"; %>
      <% end %>
      <div class="card-body">
        <div class="row">
          <div class="col-2">
            <%= image_tag post_image.user.get_profile_image(50, 50), class:"mt-3 rounded-circle"; %>
          </div>
          <div class="col-10">
            <p class="card-title">
              <%= link_to(post_image_path(post_image.id), class:"text-dark") do %>
                <strong><i class="far fa-flag"></i><span> <%= post_image.shop_name %></span></strong>
              <% end %>
            </p>
            <p class="card-text">説明: <%= post_image.caption %></p>
            <span><i class="fas fa-user"></i> By <%= post_image.user.name %> | </span>
            <span><%= render 'post_comments/count', post_image: post_image %></span>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/post_images/edit.html.erb
<h1>PostImages#edit</h1>
<p>Find me in app/views/post_images/edit.html.erb</p>

app/views/post_images/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'form', post_image: @post_image %>
    </div>
    <div class="col-md-8 offset-md-1">
      <%= render 'index', post_images: @post_images %>
    </div>
  </div>
</div>

app/views/post_images/show.html.erb
<di class="card-list-container py-5">
  <div class="card w-100 mx-auto mt-4 shadow-lg">
    <%= image_tag @post_image.get_image %>
    <div class="card-body">
      <div class="row">
        <div class="col-2">
           <%= image_tag @post_image.user.get_profile_image(50, 50), class:"mt-3 rounded-circle"; %>
        </div>
        <div class="col-10">
          <p class="card-title">
            <strong><i class="far fa-flag"></i><span> <%= @post_image.shop_name %></span></strong>
          </p>
          <p class="card-text">説明: <%= @post_image.caption %></p>
          <span><i class="fas fa-user"></i> By <%= @post_image.user.name %> | </span>
          <span><%= render 'post_comments/count', post_image: @post_image %></span>
        </div>
      </div>
    </div>
  </div>
</div>
<div>
  <%= render 'post_comments/index', post_image: @post_image, post_comments: @post_comments %>
</div>

<div>
  <%= render 'post_comments/form', post_image: @post_image, post_comment: @post_comment %>
</div>

app/views/relationships/_btn.html.erb
<% if current_user != user %>
  <% if user.followed_by?(current_user) %>
    <p><%= link_to "フォロー済み", user_relationships_path(user.id), method: :delete %></p>
  <% else %>
    <p><%= link_to "フォローする", user_relationships_path(user.id), method: :post %></p>
  <% end %>
<% end %>

app/views/users/_index.html.erb
<table class="table">
  <% users.each do |user| %>
    <tr>
      <td><%= image_tag user.get_profile_image(100, 100) %></td>
      <td>
        <%= link_to(user_path(user.id)) do %>
          <%= user.name %>
        <% end %>
      </td>
      <td>
        <%= render 'relationships/btn', user: user %>
      </td>
    </tr>
  <% end %>
</table>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<%= form_with model: @user do |f| %>
  <label for="inputName">Name</label>
  <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前" %>
  <label for="inputImage">ProfileImage</label>
  <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %>
  <%= f.submit "保存" %>
<% end %>

app/views/users/followers.html.erb
<%= render 'index', users: @users %>

app/views/users/follows.html.erb
<%= render 'index', users: @users %>

app/views/users/index.html.erb
<%= render 'index', users: @users %>

app/views/users/show.html.erb
<h1>Users#show</h1>
<div>
  <h3><%= image_tag @user.get_profile_image(100, 100) %> <%= @user.name %></h3>
  <%= render 'relationships/btn', user: @user %>
  <% if @user == current_user %>
    <p><%= link_to "プロフィール編集", edit_user_path(@user) %></p>
  <% end %>
  <%= link_to "フォロー一覧", follows_user_path %>
  <%= link_to "フォロワー一覧", followers_user_path %>
</div>

<%= render 'post_images/index', post_images: @post_images %>